[2024-04-21T20:06:02.194+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: workshop2_dags.extract_db manual__2024-04-21T19:53:36.437896+00:00 [queued]>
[2024-04-21T20:06:02.218+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: workshop2_dags.extract_db manual__2024-04-21T19:53:36.437896+00:00 [queued]>
[2024-04-21T20:06:02.219+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-04-21T20:06:02.256+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): extract_db> on 2024-04-21 19:53:36.437896+00:00
[2024-04-21T20:06:02.274+0000] {standard_task_runner.py:60} INFO - Started process 150 to run task
[2024-04-21T20:06:02.279+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'workshop2_dags', 'extract_db', 'manual__2024-04-21T19:53:36.437896+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/Airflow/dags_etl.py', '--cfg-path', '/tmp/tmpfczalt3l']
[2024-04-21T20:06:02.282+0000] {standard_task_runner.py:88} INFO - Job 33: Subtask extract_db
[2024-04-21T20:06:13.211+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 33 for task extract_db ((mysql.connector.errors.DatabaseError) 2005 (HY000): Unknown MySQL server host 'mysql' (-3)
(Background on this error at: https://sqlalche.me/e/14/4xp6); 150)
